import ThemeRegistry from "@/theme/ThemeRegistry";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/shared/navbar";
import Footer from "@/components/shared/Footer";
import Providers from "@/lib/Providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Providers>
      <html lang="en">
       
          <body className={inter.className}>
            <NavBar />
            {children}
            <Footer />
          </body>
        
      </html>
    </Providers>
  );
}
